<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp3.1-windows;net6.0-windows;net8.0-windows</TargetFrameworks>
    <UseWPF>true</UseWPF>
    <RootNamespace>AlertBarWpf</RootNamespace>
    <AssemblyName>AlertBarWpf</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>AlertBarWpf</PackageId>
    <Authors>Chad Kuehn</Authors>
    <Description>A WPF UserControl for displaying user updates through an alert bar (success, danger, warning, information).</Description>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <RepositoryUrl>https://github.com/chadkuehn/AlertBarWpf</RepositoryUrl>
    <PackageProjectUrl>https://github.com/chadkuehn/AlertBarWpf</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Resources\danger_16.png" />
    <Resource Include="Resources\warning_16.png" />
    <Resource Include="Resources\success_16.png" />
    <Resource Include="Resources\information_16.png" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE.txt" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
